const notFoundError = (res) => {
    return res.status(404).json({ error: "Este dado n√£o foi encontrado" });
};

module.exports = {
    notFoundError,
};
